### ISSUE TITLE
Creation of Wire Frames

### ISSUE THREAD

**Issue by melissay94** [melissay94/GA-Team-4#3]
### Describe the documentation: (ie sections, information needed)
- All different screen states that will be implemented for the web application.
- Components of those screens

### Why is this needed?
- Having all the screens planned out will make implementation easier for the Front End team members.

### Are you planning to add this to the Readme?
- Yes, all the wire frame drawings will go into the Readme.

**Comment by segwuonwu** [comment]
Completed the wireframes
