### ISSUE TITLE
Planning of Backend Routes

### ISSUE THREAD

**Issue by melissay94** [melissay94/GA-Team-4#4]
### Describe the documentation: (ie sections, information needed)
- All GET routes to access different screens
- All GET routes that hit API endpoints
- All POST routes for creating new DB entries
- All PUT routes for editing entries in the DB
- All DELETE routes for deleting entries in the DB

### Why is this needed?
- Planning of the routes and who is calling what will help with file structuring.

### Are you planning to add this to the Readme?
- Absolutely this is going in the Readme.

**Comment by melissay94** [comment]
Added initial event routes to Readme
Need some more routes about the user stuff.

**Comment by shawhien** [comment]
Routes have been created and are being coded by Solomon
